version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: make -s build
  test:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: make -s test
  coverage_default:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: CFLAGS='-coverage' LDFLAGS='-lgcov' make -s
      - run: gcov -abcflmpru $(find . -name '*.o')
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  coverage_debug:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: CFLAGS='-coverage -g -DDEBUG' LDFLAGS='-lgcov' make -s
      - run: gcov -abcflmpru $(find . -name '*.o')
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  coverage_O2:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - run: CFLAGS='-coverage -O2' LDFLAGS='-lgcov' make -s
      - run: gcov -abcflmpru $(find . -name '*.o')
      - run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  coverage:
    jobs:
      - coverage_default
      - coverage_debug
      - coverage_O2
