version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: make -s build
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: make -s test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
